/* usart.c - Auto-generated by CubeIDE */

#include "usart.h"

/* -------------------------------------------------------
   This is the UART handle — used everywhere in your code
   e.g. HAL_UART_Transmit(&huart2, ...)
------------------------------------------------------- */
UART_HandleTypeDef huart2;

/* -------------------------------------------------------
   UART2 Initialization Function
   PA2 = TX, PA3 = RX
   Baud: 115200, 8 bits, No parity, 1 stop bit
------------------------------------------------------- */
void MX_USART2_UART_Init(void)
{
    huart2.Instance        = USART2;
    huart2.Init.BaudRate   = 115200;
    huart2.Init.WordLength = UART_WORDLENGTH_8B;
    huart2.Init.StopBits   = UART_STOPBITS_1;
    huart2.Init.Parity     = UART_PARITY_NONE;
    huart2.Init.Mode       = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl  = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;

    if (HAL_UART_Init(&huart2) != HAL_OK)
    {
       // Error_Handler();   // stops execution if UART fails to init
    }
}

/* -------------------------------------------------------
   MSP Init — configures the actual GPIO pins for UART
   This is called automatically inside HAL_UART_Init()
------------------------------------------------------- */
void HAL_UART_MspInit(UART_HandleTypeDef* uartHandle)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    if (uartHandle->Instance == USART2)
    {
        /* Enable clocks */
        __HAL_RCC_USART2_CLK_ENABLE();
        __HAL_RCC_GPIOA_CLK_ENABLE();

        /* PA2 = USART2_TX
           PA3 = USART2_RX
           Mode: Alternate Function, Push-Pull, No Pull, High Speed */
        GPIO_InitStruct.Pin       = GPIO_PIN_2 | GPIO_PIN_3;
        GPIO_InitStruct.Mode      = GPIO_MODE_AF_PP;
        GPIO_InitStruct.Pull      = GPIO_NOPULL;
        GPIO_InitStruct.Speed     = GPIO_SPEED_FREQ_VERY_HIGH;
        GPIO_InitStruct.Alternate = GPIO_AF7_USART2;  // AF7 = USART2 on STM32F4

        HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
    }
}
