/* usart.h - Auto-generated by CubeIDE */

#ifndef __USART_H__
#define __USART_H__

#ifdef __cplusplus
extern "C" {
#endif

/* -------------------------------------------------------
   Includes
------------------------------------------------------- */
#include "main.h"

/* -------------------------------------------------------
   External variable declaration
   (actual variable is defined in usart.c)
------------------------------------------------------- */
extern UART_HandleTypeDef huart2;   // ← This is the most important line!

/* -------------------------------------------------------
   Function declaration
------------------------------------------------------- */
void MX_USART2_UART_Init(void);

#ifdef __cplusplus
}
#endif

#endif /* __USART_H__ */
